# Generated by Django 3.2.9 on 2021-12-02 11:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('item_id', models.PositiveIntegerField(null=True)),
                ('descendants', models.PositiveIntegerField(null=True)),
                ('score', models.PositiveIntegerField(null=True)),
                ('url', models.URLField(max_length=2000, null=True)),
                ('time', models.PositiveIntegerField(null=True)),
                ('is_hackernews', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Items',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.PositiveIntegerField(null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
                ('time', models.PositiveBigIntegerField(null=True)),
                ('is_hacker_comment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hakernews_api.item')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'ordering': ['time'],
            },
        ),
    ]
